# Main configuration file for NoCheatPlus. Read "Instructions.txt"
logging:
  active: true
  debugmessages: false
  prefix: '&4NCP&f: '
  filename: nocheatplus.log
  file: true
  console: true
  ingamechat: true
miscellaneous:
  allowclientmods: false
  opbyconsoleonly: true
  protectplugins: true
checks:
  blockbreak:
    fastbreak:
      active: true
      intervalsurvival: 45
      intervalcreative: 145
      actions: cancel vl>100 log:bbfastbreak:3:5:cif cancel vl>1000 log:bbfastbreak:3:5:cif cmd:kick cancel
    reach:
      active: true
      actions: cancel vl>5 log:bbreach:0:2:if cancel
    direction:
      active: true
      precision: 50
      penaltytime: 300
      actions: cancel vl>10 log:bbdirection:0:5:if cancel
    noswing:
      active: true
      actions: log:bbnoswing:3:2:if cancel
  blockplace:
    fastplace:
      active: true
      interval: 95
      actions: cancel vl>100 log:bpfastplace:3:5:cif cancel vl>1000 log:bpfastplace:3:5:cif cmd:kick cancel
    reach:
      active: true
      actions: cancel vl>5 log:bpreach:0:2:if cancel
    direction:
      active: true
      precision: 75
      penaltytime: 100
      actions: cancel vl>10 log:bpdirection:0:3:if cancel
    projectile:
      active: true
      interval: 150
      actions: cancel vl>150 log:bpprojectile:3:5:if cancel vl>1000 log:bpprojectile:3:5:cif cancel vl>4000 log:bpprojectile:3:5:cif cancel cmd:kick
    fastsign:
      exclusions:
      - '[public]'
      - '[private]'
      - '[protection]'
      - '[mail]'
      - '[free]'
      - '[kit]'
      - '[disposal]'
      - '[heal]'
      - '[time]'
      - '[weather]'
      - '[warp]'
      - '[spawnmob]'
      - '[enchant]'
      - '[trade]'
      - '[buy]'
      - '[sell]'
      - '[balance]'
      - '[gate]'
      - '[bridge]'
      - '[door]'
  chat:
    nopwnage:
      active: true
      warnplayers: true
      warnothers: false
      warnlevel: 400
      warntimeout: 30000
      banlevel: 800
      otheractions: cancel log:nopwnage:2:5:cf cmd:ban cmd:ban-ip
      move:
        active: true
        weightbonus: 200
        weightmalus: 200
        timeout: 30000
      repeat:
        active: true
        weight: 150
        timeout: 5000
      speed:
        active: true
        weight: 200
        timeout: 500
      first:
        active: true
        weight: 200
        timeout: 3000
      global:
        active: true
        weight: 100
        timeout: 5000
      banned:
        active: true
        weight: 200
        timeout: 2000
      relog:
        active: true
        time: 1500
        warnings: 1
        timeout: 60000
      captcha:
        active: true
        tries: 20
        length: 4
        characters: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
      messages:
        kick: You're not allowed to spam this server!
        captchaquestion: '&cPlease type ''&6[captcha]&c'' to continue sending messages/commands.'
        captchasuccess: '&aOK, it sounds like you''re not a spambot.'
        warnplayer: '&cOur system has detected unusual bot activities coming from you. Please be careful with what you say. DON''T repeat what you just said either, unless you want to be banned.'
        warnothers: '&cPlease do not say anything similar to what [player] said!'
        warnrelog: '&cYou relogged really fast! If you keep doing that, you''re going to be banned.'
    arrivalslimit:
      active: false
      playerslimit: 3
      timeframe: 5000
      cooldowndelay: 5000
      newtime: 600000
      kickmessage: Please try again later!
      actions: cancel
    color:
      active: true
      actions: log:color:0:1:if cancel
  fight:
    direction:
      active: true
      precision: 75
      penaltytime: 500
      actions: cancel vl>5 log:fdirection:3:5:f cancel vl>20 log:fdirection:0:5:if cancel vl>50 log:fdirection:0:5:cif cancel
    noswing:
      active: true
      actions: log:fnoswing:0:5:cif cancel
    reach:
      active: true
      distance: 400
      penaltytime: 500
      actions: cancel vl>10 log:freach:2:5:if cancel
    speed:
      active: true
      attacklimit: 15
      actions: log:fspeed:0:5:if cancel
    godmode:
      active: true
      actions: log:fgod:2:5:if cancel
    instantheal:
      active: true
      actions: log:fheal:1:1:if cancel
    knockback:
      active: true
      interval: 50
      actions: cancel vl>50 log:fknock:0:5:cif cancel
    critical:
      active: true
      falldistance: 0.01
      velocity: 0.1
      actions: cancel vl>50 log:fcritical:0:5:cif cancel
    angle:
      active: true
      threshold: 50.0
      actions: cancel vl>100 log:fangle:3:5:f cancel vl>250 log:fangle:0:5:cif cancel
  inventory:
    drop:
      active: true
      time: 20
      limit: 100
      actions: log:drop:0:1:cif cmd:kick
    instantbow:
      active: true
      actions: log:ibow:2:5:if cancel
    instanteat:
      active: true
      actions: log:ieat:2:5:if cancel
  moving:
    runfly:
      active: false
      allowfastsneaking: true
      allowfastblocking: true
      actions: log:moveshort:3:5:f cancel vl>100 log:moveshort:0:5:if cancel vl>400 log:movelong:0:5:cif cancel
      nofall:
        active: true
        aggressivemode: true
        actions: log:nofall:0:5:cif cancel
      flying:
        allowflyingalways: true
        allowflyingincreative: true
        flyingspeedlimitvertical: 100
        flyingspeedlimithorizontal: 60
        flyingheightlimit: 128
        actions: log:moveshort:3:5:f cancel vl>100 log:moveshort:0:5:if cancel vl>400 log:movelong:0:5:cif cancel
      bedflying:
        active: true
        actions: log:bedfly:3:5:f cancel vl>1 log:bedfly:0:5:if cancel vl>4 log:bedfly:0:5:cif cancel
    morepackets:
      active: true
      actions: log:morepackets:3:2:if cancel vl>20 log:morepackets:0:2:if cancel
    morepacketsvehicle:
      active: true
      actions: log:morepackets:0:2:if cancel
    waterwalk:
      active: true
      actions: log:waterwalk:3:5:f vl>100 log:waterwalk:0:5:if cancel vl>400 log:waterwalk:0:5:cif cancel
strings:
  drop: '[player] failed [check]: tried to drop more items than allowed. VL [violations].'
  moveshort: '[player] failed [check]. VL [violations].'
  movelong: '[player] in [world] at [location] moving to [locationto] over distance [movedistance] failed check [check]. Total violation level so far [violations].'
  bedfly: '[player] failed [check]: tried to fly by sending bed leaving packets. VL [violations].'
  nofall: '[player] failed [check]: tried to avoid fall damage for ~[falldistance] blocks. VL [violations].'
  morepackets: '[player] failed [check]: sent [packets] more packets than expected. Total violation level [violations].'
  waterwalk: '[player] failed [check]: tried to walk on water. Total violation level [violations].'
  bbfastbreak: '[player] failed [check]: tried to break too much [blocktype]. Total violation level [violations].'
  bbreach: '[player] failed [check]: tried to interact with a block over distance [reachdistance]. VL [violations].'
  bbdirection: '[player] failed [check]: tried to interact with a block out of line of sight. VL [violations].'
  bbnoswing: '[player] failed [check]: Didn''t swing arm. VL [violations].'
  bpfastplace: '[player] failed [check]: tried to place too much blocks. Total violation level [violations].'
  bpreach: '[player] failed [check]: tried to interact with a block over distance [reachdistance]. VL [violations].'
  bpdirection: '[player] failed [check]: tried to interact with a block out of line of sight. VL [violations].'
  bpprojectile: '[player] failed [check]: tried to throw items too quicly. VL [violations].'
  nopwnage: '[player] ([ip]) failed chat.nopwnage: [reason].'
  color: '[player] failed [check]: sent colored chat message ''[text]''. VL [violations].'
  fdirection: '[player] failed [check]: tried to interact with a block out of line of sight. VL [violations].'
  freach: '[player] failed [check]: tried to attack entity out of reach. VL [violations].'
  fspeed: '[player] failed [check]: tried to attack more than [limit] times per second. VL [violations].'
  fnoswing: '[player] failed [check]: Didn''t swing arm. VL [violations].'
  fgod: '[player] failed [check]: Avoided taking damage or lagging. VL [violations].'
  fheal: '[player] failed [check]: tried to regenerate health faster than normal. VL [violations].'
  fknock: '[player] failed [check]: tried to do a knockback but wasn''t technically sprinting. VL [violations].'
  fcritical: '[player] failed [check]: tried to do a critical hit but wasn''t technically jumping. VL [violations].'
  fangle: '[player] failed [check]: tried to fight multiple entities at the same time. VL [violations].'
  ibow: '[player] failed [check]: fires bow to fast. VL [violations].'
  ieat: '[player] failed [check]: eats food [food] too fast. VL [violations].'
  kick: kick [player]
  ban: ban [player]
  ban-ip: ban-ip [ip]
